version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: NewRootPass
      MYSQL_DATABASE: project
      MYSQL_USER: new_user
      MYSQL_PASSWORD: Pass2025
    ports:
      - '3307:3306'
    volumes:
      - mysqlDb:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6380:6379'
    volumes:
      - redisData:/data
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9094:9092"
    volumes:
      - kafkaData:/var/lib/kafka
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.19.5
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: kibana:8.19.5
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
      - TELEMETRY_ENABLED=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped


volumes:
  mysqlDb:
  redisData:
  kafkaData:
  es_data: